openapi: '3.0.0'
info:
  title: My Financy
  version: 1.0.0
paths:
  /health:
    get:
      summary: Verificar o status de saúde da API
      description: Retorna uma mensagem 'OK!' para indicar que a API está funcionando corretamente.
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example:
                message: 'OK!'

  /users:
    post:
      summary: Criar usuário
      description: Retorna informações sobre os usuários da aplicação.
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example:
                users:
                  [
                    {
                      'id': number,
                      'email': 'email',
                      'password': 'token',
                      'name': 'Kaio',
                    },
                  ]

  /auth:
    post:
      summary: Autenticar usuário
      description: Autentica um usuário e retorna um token de acesso.
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: 'example_user'
              password: 'example_password'
      responses:
        '200':
          description: Sucesso
          content:
            application/json:
              example:
                token: 'example_token'
